### ISSUE TITLE
Is this needed for building from the release tarballs?

### ISSUE THREAD

**Issue by frimam** [mate-desktop/mate-common#17]
I wonder wether this package is really needed if I don't build from the git repositories of the other MATE packages, because in the release tarball autogen.sh doesn't need to be run. But for example the Arch Linux PKGBUILD for caja mentiones it as a make dependency (see https://github.com/mate-desktop/archlinux-packages/blob/master/caja/PKGBUILD).

**Comment by raveit65** [comment]
Well, i don't think that any package needs it as direct dependency. When Mate was started we didn't use 'make dist' to create a tarball, so it was needed to create the make files before building. And for fedora we use it to pull in some general deps to build the mate stack.
Btw. mentioned mate-icon-theme in your link can be removed for sure.

**Comment by frimam** [comment]
Ok, thanks. I just wanted to be sure wether there's nothing affected when I build it without mate-common.
