### ISSUE TITLE
Debian Unstable: "shift" error in mate-autogen stops configuration

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-common#19]
Any attempt to configure a mate package other than mate-common (which can't use mate-autogen as it may not be installed yet) got this error after my latest round of Debian Unstable updates:

` ./autogen.sh: 80: shift: can't shift that many`

Configuration stops at that point, changing the shell used by the script to bash (pretty sure dash is default) had no effect.

I was able to get past this for now by commenting lines 79-84, the entire loop containing "shift" used in version checking. I won't get a any notice of a missing/too old package this way (just build errors) but at least I can still build the MATE packages until either Debian finds a problem with one of their packages or a fix for this is found here, possibly by comparing to GNOME's version.

Somewhere between July 16 and July 28 Debian Unstable got an update that changed what is presumably shell behavior and breaks something in the usage of the shift command in /usr/bin/mate-autogen . The superficially similar gnome-autogen.sh did not seem to be affected, I was able to configure Nautilus without issue.

Sorry about the big gap between Debian updates, I don't have landline service at home and can only update packages from machines set up elsewhere or over public access wifi. I do not control the house and cannot set up any kind of utilities.

**Comment by raveit65** [comment]
For the momment 'autoreconf -fi ' should do the same job.

**Comment by monsta** [comment]
@flexiondotorg @sunweaver
Do you guys know anything about these updates in Unstable?

**Comment by monsta** [comment]
> The superficially similar gnome-autogen.sh did not seem to be affected, I was able to configure Nautilus without issue.

Weird... the code in gnome-common seems to be the same:
https://sources.debian.net/src/gnome-common/3.18.0-2/macros2/gnome-autogen.sh/#L80

**Comment by monsta** [comment]
Ah... maybe they already migrated away from it?

https://wiki.gnome.org/Projects/GnomeCommon/Migration

**Comment by lukefromdc** [comment]
I found a very simiar autogen script in my gnome-common install, may
try it as the basis for a fix

**Comment by lukefromdc** [comment]
I just found the commented out code gets around the problem, but GNOME uses the exact same code in that part of their script and cut and pasting it in brings back the shift error. My guess is this has something to do with the invocation of the shell or possibly with exactly which shell is invoked, probably the former as I tried specifying bash (heavy but complete) at the top of the script and got the same results.  

No change in Debian has fixed this as of August 12, 2016, just reinstalled mate-common for a test and got the same results, had to return to the workaround solution but it invalidates some tests of configure.ac files in any other package.

**Comment by sc0w** [comment]
same problem in:

**caja-actions
mate-indicator-applet
mate-power-manager
caja-dropbox
atril
caja-extensions**

https://bugs.debian.org/cgi-bin/pkgreport.cgi?include=subject%3AFTBFS;maint=pkg-mate-team%40lists.alioth.debian.org

**Comment by flexiondotorg** [comment]
I was researching this yesterday. I am going to implement the following commit from `gnome-common`:

  * https://git.gnome.org/browse/gnome-common/commit/macros2/gnome-autogen.sh?id=17f56a49964a3ddabf0d166326989033b7d84764

**Comment by flexiondotorg** [comment]
@monsta @lukefromdc See above for a patch.

**Comment by flexiondotorg** [comment]
A patched `mate-common` Debian package has been uploaded to Debian unstable.
